//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezuniyetOtomasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AkademikYil
    {
        public int AY_Id { get; set; }
        public string Descriptor { get; set; }
        public string Adi { get; set; }
        public Nullable<System.DateTime> Baslangic_Tarihi { get; set; }
        public Nullable<System.DateTime> Bitis_Tarihi { get; set; }
        public Nullable<int> AYStatu { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ModUserId { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<int> birimtip { get; set; }
        public string Yil { get; set; }
    }
}
