//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezuniyetOtomasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BireyBirimIliskisi
    {
        public Nullable<int> Birey_Id { get; set; }
        public Nullable<int> Birim_Id { get; set; }
        public int BBI_Id { get; set; }
        public string OgrenciNo { get; set; }
        public Nullable<int> Relation_Type { get; set; }
        public Nullable<int> Statu { get; set; }
        public Nullable<int> Hazirlik { get; set; }
        public Nullable<int> HazirlikYili { get; set; }
        public Nullable<int> HazirlikNotu { get; set; }
        public Nullable<int> Okudugu_Donem { get; set; }
        public Nullable<int> AkademikDonem { get; set; }
        public string GelmeSekli { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public Nullable<System.DateTime> AyrilisTarihi { get; set; }
        public Nullable<double> BolumDerecesi { get; set; }
        public Nullable<int> BursStatu { get; set; }
        public Nullable<int> HarcStatu { get; set; }
        public Nullable<int> Ay_Id { get; set; }
        public Nullable<int> OkulTip { get; set; }
        public string OkulTuru { get; set; }
        public string GeldigiOkul { get; set; }
        public Nullable<int> BolumTip { get; set; }
        public string GeldigiBolum { get; set; }
        public Nullable<System.DateTime> MezuniyetTarihi { get; set; }
        public Nullable<double> NotOrtalamasi { get; set; }
        public Nullable<int> DiplomaNo { get; set; }
        public Nullable<double> LESPuaniSay { get; set; }
        public Nullable<double> LESPuaniSoz { get; set; }
        public Nullable<double> LESPuaniEA { get; set; }
        public Nullable<double> LESPuaniDIL { get; set; }
        public Nullable<System.DateTime> LESTarihi { get; set; }
        public Nullable<double> GirisPuani { get; set; }
        public string Gorev { get; set; }
        public string Aciklama { get; set; }
        public string Sinif { get; set; }
        public Nullable<int> KayitAY_Id { get; set; }
        public Nullable<int> YonetmelikTuru { get; set; }
        public Nullable<int> KayitDonem { get; set; }
        public Nullable<int> StajDurumu { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ModUserId { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<int> DiplomaAlindi { get; set; }
        public Nullable<System.DateTime> DiplomaTarihi { get; set; }
        public string TCKimlikNo { get; set; }
        public Nullable<double> EgitimYili { get; set; }
        public Nullable<int> IkinciUniversiteOkuduMu { get; set; }
        public Nullable<int> Harcgec { get; set; }
        public Nullable<int> Asamasi { get; set; }
        public string transfer { get; set; }
        public Nullable<int> Gelbolkod { get; set; }
        public Nullable<int> Girbolkod { get; set; }
        public Nullable<double> Kredi { get; set; }
        public Nullable<double> GNO5 { get; set; }
        public Nullable<double> GNO { get; set; }
        public Nullable<int> uyruk { get; set; }
        public Nullable<System.DateTime> OrtModDate { get; set; }
        public Nullable<int> Onay { get; set; }
        public string OnKayitNo { get; set; }
        public Nullable<int> OnKayitBasvuruDonemId { get; set; }
        public Nullable<int> MezAY_Id { get; set; }
        public Nullable<int> MezSomestre { get; set; }
        public Nullable<int> OgrYariyil { get; set; }
        public string Seviye { get; set; }
        public string OgrHakKaybetTar { get; set; }
        public Nullable<int> CapBirey_Id { get; set; }
        public string ogrnomanolya { get; set; }
        public Nullable<int> KayitDondurma { get; set; }
        public Nullable<System.DateTime> IslemTarihYKK { get; set; }
    }
}
