//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezuniyetOtomasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Birey
    {
        public int Birey_Id { get; set; }
        public string Descriptor { get; set; }
        public string Unvan { get; set; }
        public string UzmanlikAlani { get; set; }
        public string UzmanlikKaynak { get; set; }
        public string SicilNo { get; set; }
        public string OgrenciNo { get; set; }
        public string OSYMNO { get; set; }
        public string isim { get; set; }
        public string soyad { get; set; }
        public Nullable<System.DateTime> dogum_tarihi { get; set; }
        public string dogum_yeri { get; set; }
        public Nullable<int> medeni_durum { get; set; }
        public Nullable<int> cinsiyeti { get; set; }
        public string anne_adi { get; set; }
        public string baba_adi { get; set; }
        public string aciklama { get; set; }
        public byte[] resim { get; set; }
        public string uyrugu { get; set; }
        public string nc_kimlik_no { get; set; }
        public string nc_ili { get; set; }
        public string nc_ilcesi { get; set; }
        public string nc_mahal_koy { get; set; }
        public string nc_seri_no { get; set; }
        public string nc_kayit_no { get; set; }
        public string nc_cilt_no { get; set; }
        public string nc_aile_sira_no { get; set; }
        public string nc_kutuk_sira_no { get; set; }
        public string nc_verildigi_yer { get; set; }
        public string nc_verilis_nedeni { get; set; }
        public Nullable<System.DateTime> nc_verilis_tarihi { get; set; }
        public Nullable<int> askerlik { get; set; }
        public string askerlik_sube { get; set; }
        public Nullable<System.DateTime> tecil_suresi { get; set; }
        public string dini { get; set; }
        public Nullable<int> kan_grubu { get; set; }
        public string PasaportNo { get; set; }
        public Nullable<System.DateTime> PasaportTarihi { get; set; }
        public Nullable<System.DateTime> VizeAlmaTarihi { get; set; }
        public string GecerlilikSuresi { get; set; }
        public string YokSis { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ModUserId { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<int> IDOGRENCI { get; set; }
        public Nullable<int> blmkod { get; set; }
        public Nullable<int> Birim_Id { get; set; }
        public Nullable<int> KISIID { get; set; }
        public Nullable<int> TurkAsilli { get; set; }
        public string dogum_yeri_diger { get; set; }
        public string sube { get; set; }
        public string yokogrencino { get; set; }
    }
}
