//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezuniyetOtomasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Birimler
    {
        public int Birim_Id { get; set; }
        public int BT_Id { get; set; }
        public string Birim_Kodu { get; set; }
        public string Birim_Adi { get; set; }
        public string Birim_KisaAd { get; set; }
        public string Birim_Adi_ENG { get; set; }
        public string BirimDesimalKodu { get; set; }
        public string VerdigiUnvan { get; set; }
        public Nullable<int> Kapasite { get; set; }
        public Nullable<int> Ogretim_Dili { get; set; }
        public Nullable<int> Ogretim_Tipi { get; set; }
        public string Aciklama { get; set; }
        public string www { get; set; }
        public Nullable<int> Donem { get; set; }
        public string Adres { get; set; }
        public Nullable<int> Azami { get; set; }
        public Nullable<int> AzamiDonem { get; set; }
        public Nullable<int> BirimTip { get; set; }
        public Nullable<int> Statu { get; set; }
        public string OSYMKodu { get; set; }
        public Nullable<int> PuanTuru { get; set; }
        public Nullable<int> AlisSekli { get; set; }
        public Nullable<int> Hazirlik { get; set; }
        public Nullable<int> HazirlikTipi { get; set; }
        public Nullable<System.DateTime> KurulusTarihi { get; set; }
        public byte[] Logo { get; set; }
        public string OsymBursluKodu { get; set; }
        public string OsymBurssuzKodu { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ModUserId { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<int> YoKSisID { get; set; }
        public Nullable<int> BasPuan { get; set; }
        public Nullable<int> PuanTurYL { get; set; }
        public string HarcAzami { get; set; }
        public Nullable<int> dilsinavi { get; set; }
        public Nullable<double> Lisansort { get; set; }
        public string dilpuani { get; set; }
        public Nullable<int> Birimseviye { get; set; }
        public string KimlikKisaAd { get; set; }
        public string Anabilimdali { get; set; }
        public Nullable<int> YKKBirim_Id { get; set; }
        public Nullable<int> Fakulte_Id { get; set; }
        public string Fakulte_Adi { get; set; }
        public string BirimDipDefAd { get; set; }
        public string UstBirimAd { get; set; }
        public string DipDefterisim { get; set; }
    }
}
