//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezuniyetOtomasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MezuniyetDetay
    {
        public int id { get; set; }
        public Nullable<int> Birey_Id { get; set; }
        public Nullable<System.DateTime> MezTar { get; set; }
        public Nullable<bool> Cuppe { get; set; }
        public Nullable<int> AY_Id { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ModUserId { get; set; }
        public Nullable<System.DateTime> ModUserDate { get; set; }
        public Nullable<System.DateTime> CuppeAlimTarih { get; set; }
        public Nullable<System.DateTime> CuppeTeslimTarih { get; set; }
    }
}
