//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezuniyetOtomasyon.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NoktaGSUEntities : DbContext
    {
        public NoktaGSUEntities()
            : base("name=NoktaGSUEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Birey> Birey { get; set; }
        public virtual DbSet<BireyBirimIliskisi> BireyBirimIliskisi { get; set; }
        public virtual DbSet<Birimler> Birimler { get; set; }
        public virtual DbSet<UserGroup> UserGroup { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Adres> Adres { get; set; }
        public virtual DbSet<Iletisim> Iletisim { get; set; }
        public virtual DbSet<AkademikYil> AkademikYil { get; set; }
        public virtual DbSet<MezuniyetDetay> MezuniyetDetay { get; set; }
    
        public virtual ObjectResult<USP_Son50MezunGetir_Result> USP_Son50MezunGetir(Nullable<int> mezunSayisi)
        {
            var mezunSayisiParameter = mezunSayisi.HasValue ?
                new ObjectParameter("MezunSayisi", mezunSayisi) :
                new ObjectParameter("MezunSayisi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Son50MezunGetir_Result>("USP_Son50MezunGetir", mezunSayisiParameter);
        }
    }
}
